# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import face_pb2 as face__pb2


class FaceServiceStub(object):
    """============================================================================
    Face Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectFaces = channel.unary_unary(
                '/sssp.ai.face.FaceService/DetectFaces',
                request_serializer=face__pb2.FaceDetectRequest.SerializeToString,
                response_deserializer=face__pb2.FaceDetectResponse.FromString,
                )
        self.RecognizeFace = channel.unary_unary(
                '/sssp.ai.face.FaceService/RecognizeFace',
                request_serializer=face__pb2.FaceRecognizeRequest.SerializeToString,
                response_deserializer=face__pb2.FaceRecognizeResponse.FromString,
                )
        self.VerifyFace = channel.unary_unary(
                '/sssp.ai.face.FaceService/VerifyFace',
                request_serializer=face__pb2.FaceVerifyRequest.SerializeToString,
                response_deserializer=face__pb2.FaceVerifyResponse.FromString,
                )
        self.EnrollFace = channel.unary_unary(
                '/sssp.ai.face.FaceService/EnrollFace',
                request_serializer=face__pb2.FaceEnrollRequest.SerializeToString,
                response_deserializer=face__pb2.FaceEnrollResponse.FromString,
                )
        self.GetModelInfo = channel.unary_unary(
                '/sssp.ai.face.FaceService/GetModelInfo',
                request_serializer=face__pb2.FaceModelInfoRequest.SerializeToString,
                response_deserializer=face__pb2.FaceModelInfoResponse.FromString,
                )
        self.ExtractEmbedding = channel.unary_unary(
                '/sssp.ai.face.FaceService/ExtractEmbedding',
                request_serializer=face__pb2.FaceEmbeddingRequest.SerializeToString,
                response_deserializer=face__pb2.FaceEmbeddingResponse.FromString,
                )


class FaceServiceServicer(object):
    """============================================================================
    Face Service
    ============================================================================

    """

    def DetectFaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFaces,
                    request_deserializer=face__pb2.FaceDetectRequest.FromString,
                    response_serializer=face__pb2.FaceDetectResponse.SerializeToString,
            ),
            'RecognizeFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFace,
                    request_deserializer=face__pb2.FaceRecognizeRequest.FromString,
                    response_serializer=face__pb2.FaceRecognizeResponse.SerializeToString,
            ),
            'VerifyFace': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyFace,
                    request_deserializer=face__pb2.FaceVerifyRequest.FromString,
                    response_serializer=face__pb2.FaceVerifyResponse.SerializeToString,
            ),
            'EnrollFace': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollFace,
                    request_deserializer=face__pb2.FaceEnrollRequest.FromString,
                    response_serializer=face__pb2.FaceEnrollResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=face__pb2.FaceModelInfoRequest.FromString,
                    response_serializer=face__pb2.FaceModelInfoResponse.SerializeToString,
            ),
            'ExtractEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEmbedding,
                    request_deserializer=face__pb2.FaceEmbeddingRequest.FromString,
                    response_serializer=face__pb2.FaceEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sssp.ai.face.FaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceService(object):
    """============================================================================
    Face Service
    ============================================================================

    """

    @staticmethod
    def DetectFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sssp.ai.face.FaceService/DetectFaces',
            face__pb2.FaceDetectRequest.SerializeToString,
            face__pb2.FaceDetectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecognizeFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sssp.ai.face.FaceService/RecognizeFace',
            face__pb2.FaceRecognizeRequest.SerializeToString,
            face__pb2.FaceRecognizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sssp.ai.face.FaceService/VerifyFace',
            face__pb2.FaceVerifyRequest.SerializeToString,
            face__pb2.FaceVerifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnrollFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sssp.ai.face.FaceService/EnrollFace',
            face__pb2.FaceEnrollRequest.SerializeToString,
            face__pb2.FaceEnrollResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sssp.ai.face.FaceService/GetModelInfo',
            face__pb2.FaceModelInfoRequest.SerializeToString,
            face__pb2.FaceModelInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExtractEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sssp.ai.face.FaceService/ExtractEmbedding',
            face__pb2.FaceEmbeddingRequest.SerializeToString,
            face__pb2.FaceEmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
