# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_stream_pb2 as video__stream__pb2


class VideoStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFrames = channel.stream_stream(
                '/sssp.ai.stream.VideoStreamService/StreamFrames',
                request_serializer=video__stream__pb2.VideoFrameRequest.SerializeToString,
                response_deserializer=video__stream__pb2.VideoFrameResponse.FromString,
                )


class VideoStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamFrames(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFrames': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=video__stream__pb2.VideoFrameRequest.FromString,
                    response_serializer=video__stream__pb2.VideoFrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sssp.ai.stream.VideoStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/sssp.ai.stream.VideoStreamService/StreamFrames',
            video__stream__pb2.VideoFrameRequest.SerializeToString,
            video__stream__pb2.VideoFrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
