# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_stream.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_stream.proto\x12\x0esssp.ai.stream\"b\n\x11VideoFrameRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x12\n\nimage_jpeg\x18\x04 \x01(\x0c\"5\n\x07\x46\x61\x63\x65\x42ox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01w\x18\x03 \x01(\x02\x12\t\n\x01h\x18\x04 \x01(\x02\"\x1f\n\rFaceEmbedding\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"d\n\nFaceResult\x12$\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x17.sssp.ai.stream.FaceBox\x12\x30\n\tembedding\x18\x02 \x01(\x0b\x32\x1d.sssp.ai.stream.FaceEmbedding\"d\n\x12VideoFrameResponse\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x03\x12)\n\x05\x66\x61\x63\x65s\x18\x03 \x03(\x0b\x32\x1a.sssp.ai.stream.FaceResult2o\n\x12VideoStreamService\x12Y\n\x0cStreamFrames\x12!.sssp.ai.stream.VideoFrameRequest\x1a\".sssp.ai.stream.VideoFrameResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOFRAMEREQUEST']._serialized_start=38
  _globals['_VIDEOFRAMEREQUEST']._serialized_end=136
  _globals['_FACEBOX']._serialized_start=138
  _globals['_FACEBOX']._serialized_end=191
  _globals['_FACEEMBEDDING']._serialized_start=193
  _globals['_FACEEMBEDDING']._serialized_end=224
  _globals['_FACERESULT']._serialized_start=226
  _globals['_FACERESULT']._serialized_end=326
  _globals['_VIDEOFRAMERESPONSE']._serialized_start=328
  _globals['_VIDEOFRAMERESPONSE']._serialized_end=428
  _globals['_VIDEOSTREAMSERVICE']._serialized_start=430
  _globals['_VIDEOSTREAMSERVICE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
