name: CI
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  api-dotnet:
    name: .NET API - Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api-dotnet
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --no-build --verbosity normal

  ai-fastapi:
    name: FastAPI - Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/ai-fastapi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: pytest -q

  web-dashboard:
    name: Web Dashboard - Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web-dashboard
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/web-dashboard/package-lock.json'
      - run: npm ci
      - run: npm run build
