name: Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**'
      - 'deploy/**'
      - '.github/workflows/**'

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

permissions:
  contents: read
  packages: write

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api-dotnet, ai-fastapi, web-dashboard]
    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        id: img
        run: echo "NAME=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/sssp-${{ matrix.app }}" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: apps/${{ matrix.app }}
          push: true
          tags: |
            ${{ steps.img.outputs.NAME }}:latest
            ${{ steps.img.outputs.NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  deploy-dev:
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy via SSH or K8s
        run: |
          echo "Pull containers and restart services on DEV environment"
          echo "Example:"
          echo "docker pull ghcr.io/${{ env.IMAGE_OWNER }}/sssp-api-dotnet:latest"
          echo "docker pull ghcr.io/${{ env.IMAGE_OWNER }}/sssp-ai-fastapi:latest"
          echo "docker pull ghcr.io/${{ env.IMAGE_OWNER }}/sssp-web-dashboard:latest"
