name: Deploy
on:
  push:
    branches: [main]
    paths: ['apps/**','deploy/**','.github/workflows/**']

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api-dotnet, ai-fastapi, web-dashboard]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: apps/${{ matrix.app }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.app }}:${{ github.sha }}

  deploy-dev:
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy via SSH or k8s
        run: |
          echo "Pull containers and restart services on DEV"
